import logging
logger = logging.getLogger('genesym')

import config

from .finder import FileFinder

from genesym import hgnc


class BioMartFinder(FileFinder):
    """
    Search in file generated by http://central.biomart.org/martwizard
    """
    def __init__(self):

        super().__init__(config.biomart_fn)

        self.hgnc_id_colname = 'HGNC ID(s)'

    def get_hgnc_id(self, row):
        if self.hgnc_id_colname in row.keys():
            return row[self.hgnc_id_colname]
        return None

    def lookup_unigene_id(self, unigene_id):
        hgnc_id = None
        hgnc_symbol = None

        # unigene lookup file has only hgnc id column, but no symbol
        df = self.lookup_fast(unigene_id, ['Unigene ID'])

        if df.shape[0] >= 1:
            # return fist match
            # TODO smarter select in non-unique case
            row = df.iloc[0]
            hgnc_id = self.get_hgnc_id(row)
            hgnc_symbol = hgnc.get_symbol_by_id(hgnc_id)
        else:
            logger.warning('Unigene ID {} is not found in file {}'.format(
                unigene_id, self.data_fn)
            )

        return hgnc_id, hgnc_symbol
